// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkU3piBOvuQyxebjPK0N7rOqtvq2xOZ8',
    appId: '1:864238800189:web:c293d2dd31e7b608a80954',
    messagingSenderId: '864238800189',
    projectId: 'learnmatch-2b5c4',
    authDomain: 'learnmatch-2b5c4.firebaseapp.com',
    storageBucket: 'learnmatch-2b5c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7E2xs-IRAozX_ZYvaHXL8_cI6IlxiCac',
    appId: '1:864238800189:android:99d9dd24ae3b5a27a80954',
    messagingSenderId: '864238800189',
    projectId: 'learnmatch-2b5c4',
    storageBucket: 'learnmatch-2b5c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9NUpDvnBS91yOUG78VWY3TEBZQB02uxA',
    appId: '1:864238800189:ios:91dd345da0a66c83a80954',
    messagingSenderId: '864238800189',
    projectId: 'learnmatch-2b5c4',
    storageBucket: 'learnmatch-2b5c4.firebasestorage.app',
    iosBundleId: 'com.example.learnMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9NUpDvnBS91yOUG78VWY3TEBZQB02uxA',
    appId: '1:864238800189:ios:91dd345da0a66c83a80954',
    messagingSenderId: '864238800189',
    projectId: 'learnmatch-2b5c4',
    storageBucket: 'learnmatch-2b5c4.firebasestorage.app',
    iosBundleId: 'com.example.learnMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnkU3piBOvuQyxebjPK0N7rOqtvq2xOZ8',
    appId: '1:864238800189:web:0492988180ca6fdea80954',
    messagingSenderId: '864238800189',
    projectId: 'learnmatch-2b5c4',
    authDomain: 'learnmatch-2b5c4.firebaseapp.com',
    storageBucket: 'learnmatch-2b5c4.firebasestorage.app',
  );
}
